DELETE https://asd-ems-db.herokuapp.com/employees
Content-Type: application/json

{
	"fname": "Jon",
  "lname": "Jones",
	"dob": "1980-10-05",
 "phoneno": "0404",
 "username": "JonJones@EMSHR",
 "pwd": "jon123",
 "accname": "jjones",
 "accnum": "1234",
 "accbsb": "111",
 "address": "12 Test st",
 "suburb": "Liverpool",
 "state": "NSW",
 "pcode": "1111",
 "employdate": "2011-10-10",
 "dept": "Operation",
 "employtype": "Full-Time",
 "id": "222"
}